services:
  web-app-php:
    build:
      context: .
    volumes:
      - .:/var/www/html
    container_name: web-app-php-service-final-project
    ports:
      - "6090:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - postgresql
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: web-app-php-mongodb-final-project
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: finalproject
    ports:
      - "26969:27017"
    volumes:
      - web-app-php-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: web-app-php-postgresql-final-project
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finalproject
    ports:
      - "5269:5432"
    volumes:
      - web-app-php-postgresql:/data/db/postgresql

volumes:
  web-app-php-mongodb:
    driver: local
  web-app-php-postgresql:
    driver: local