CREATE TABLE IF NOT EXISTS users (
  id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(225) NOT NULL UNIQUE,
  password VARCHAR(225) NOT NULL,
  name VARCHAR(225) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'user'
);